<div style="background: linear-gradient(135deg, #0072B2 0%, #004f7a 100%); color: #ffffff; padding: 32px 38px; border-radius: 12px; margin: 0 0 22px 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;"><div style="font-size: 11px; letter-spacing: 2.5px; text-transform: uppercase; opacity: 0.75; margin-bottom: 6px; font-weight: 500;">Analyse de Données avec Python pour Professionnels de la Santé</div><h1 style="margin: 0; font-size: 30px; font-weight: 600; color: #ffffff; line-height: 1.2; border: none; padding: 0;"><span style="opacity: 0.65; font-weight: 400;">Module 2</span><span style="opacity: 0.4; margin: 0 12px;">·</span>Nettoyage et descriptif</h1><div style="margin-top: 14px; font-size: 14px; opacity: 0.9;">Version condensee 6 heures  ·  Module 2 sur 6  ·  Duree 60 minutes</div></div><div style="margin: 0 0 22px 0;"><span style="display: inline-block; background: #e8f4f8; color: #005c8f; padding: 5px 14px; border-radius: 14px; font-size: 12px; margin: 0 6px 6px 0; font-weight: 500; border: 1px solid #b8dde9; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">Niveau debutant</span><span style="display: inline-block; background: #fff4eb; color: #a64a00; padding: 5px 14px; border-radius: 14px; font-size: 12px; margin: 0 6px 6px 0; font-weight: 500; border: 1px solid #f0c89d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">Duree 60 min</span><span style="display: inline-block; background: #f5f0fa; color: #5a3380; padding: 5px 14px; border-radius: 14px; font-size: 12px; margin: 0 6px 6px 0; font-weight: 500; border: 1px solid #d4c0e8; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">Prerequis : Module 1</span><span style="display: inline-block; background: #f3f3f3; color: #555555; padding: 5px 14px; border-radius: 14px; font-size: 12px; margin: 0 6px 6px 0; font-weight: 500; border: 1px solid #d0d0d0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">Colab compatible</span></div><div style="margin: 0 0 18px 0;"><a href="https://colab.research.google.com/github/gabayae/-python-sante/blob/main/notebooks_vierges/module_02_nettoyage_descriptif.ipynb" target="_blank" style="text-decoration: none;"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" style="vertical-align: middle;"/></a></div><div style="border: 1px solid #e0e0e0; border-left: 4px solid #009E73; background: #fafbfc; padding: 18px 22px; margin: 20px 0; border-radius: 0 6px 6px 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;"><div style="font-size: 11px; letter-spacing: 1.5px; color: #009E73; font-weight: 600; margin-bottom: 10px;">OBJECTIFS DU MODULE</div><ul style="margin: 0; padding-left: 22px; color: #333; font-size: 14px;"><li style="margin: 6px 0; line-height: 1.5;">Diagnostiquer les <strong>valeurs manquantes</strong> (MCAR / MAR / MNAR) et choisir une strategie défendable.</li><li style="margin: 6px 0; line-height: 1.5;">Standardiser des données incoherentes (dates, codes, unites).</li><li style="margin: 6px 0; line-height: 1.5;">Valider les valeurs contre des <strong>plages cliniquement plausibles</strong>.</li><li style="margin: 6px 0; line-height: 1.5;">Construire un <strong>pipeline de nettoyage</strong> reutilisable.</li><li style="margin: 6px 0; line-height: 1.5;">Calculer les mesures de <strong>tendance centrale</strong> et de <strong>dispersion</strong>.</li><li style="margin: 6px 0; line-height: 1.5;">Calculer les mesures <strong>épidémiologiques</strong> de base : prévalence, incidence, RR, OR avec leurs IC.</li></ul></div><div style="border-left: 4px solid #D55E00; background: #fff4eb; padding: 14px 18px; margin: 18px 0; border-radius: 0 6px 6px 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;"><div style="font-weight: 600; color: #a64a00; font-size: 11px; letter-spacing: 1.2px; margin-bottom: 6px;">POURQUOI CE MODULE EST CENTRAL</div><div style="color: #333; font-size: 14px; line-height: 1.5;">Le nettoyage est un <strong>raisonnement clinique</strong> écrit en code. Chaque décision (supprimer, imputer, signaler) deplace l'analyse. La discipline consiste a <strong>documenter chaque choix</strong> pour qu'un relecteur puisse le reproduire.<br><br>Reference fondatrice : Rubin DB, <em>Inference and Missing Data</em>, Biometrika 1976.</div></div>

## 0. Imports et reproductibilité

> **Syntaxe — import multiple**
> ```python
> import a, b              # rare, évite par convention
> import a                 # une ligne par module - préfère
> import b
> ```
> On regroupe les imports en tête : standard library d'abord, puis tierces parties.

In [1]:
import math                            # fonctions mathématiques scalaires
import numpy as np                     # tableaux numériques
import pandas as pd                    # tables
import matplotlib.pyplot as plt        # graphiques
from scipy import stats                # stats inferentielles

np.random.seed(42)                     # graine reproductibilité
pd.set_option("display.width", 100)    # largeur d'affichage console

## 1. Les trois mécanismes de données manquantes

Tout traitement des valeurs manquantes depend de leur **mécanisme** (Rubin 1976) :

- **MCAR — Missing Completely At Random.** Independant du reste. Exemple : un tube de prelevement casse. Supprimer est sans biais.
- **MAR — Missing At Random.** Depend de variables **observees**. Exemple : le cholesterol n'est pas mesure chez les jeunes. Imputer en tenant compte de l'age est sans biais.
- **MNAR — Missing Not At Random.** Depend de la valeur **non observee**. Exemple : les patients les plus malades ratent leurs rendez-vous. Supprimer biaise vers les patients en bonne santé.

> Dans les dossiers electroniques, MNAR est la **règle**, pas l'exception. Toujours vérifier si l'issue differe entre lignes completes et lignes a données manquantes.

Lecture recommandée : Little RJA & Rubin DB, *Statistical Analysis with Missing Data*, 3e ed., Wiley 2019.

## 2. Detection avec pandas

Pandas utilise **`NaN`** (Not a Number) pour les valeurs manquantes numériques, et `None` pour les objets. Les deux sont détectés par `.isnull()` (alias : `.isna()`).

> **Syntaxe — creer un DataFrame a la main**
> ```python
> df = pd.DataFrame({
>     "col1": [v1, v2, v3, ...],
>     "col2": [w1, w2, w3, ...],
> })
> ```
> Chaque clé du dictionnaire devient un nom de colonne, chaque liste les valeurs de la colonne.

> **Syntaxe — détection NaN**
> ```python
> df.isnull()           # DataFrame de True/False, même taille
> df.isnull().sum()     # nb manquant par colonne
> df.isnull().any(axis=1)   # True/False par ligne (au moins un NaN)
> ```

In [2]:
# Petit DataFrame clinique avec des manquements deliberes
# np.nan est la valeur 'NaN' (Not a Number) de numpy.
données = {
    "patient_id":  ["P001", "P002", "P003", "P004", "P005", "P006"],
    "age":         [45, 67, 34, np.nan, 71, 52],          # 1 manquant
    "sexe":        ["M", "F", "F", "M", np.nan, "F"],   # 1 manquant
    "tension":     [128, 158, np.nan, 145, 162, np.nan],   # 2 manquants
    "hba1c":       [5.4, 7.8, 5.1, np.nan, 8.2, 6.3],      # 1 manquant
}
df = pd.DataFrame(données)
df

  patient_id   age sexe  tension  hba1c
0       P001  45.0    M    128.0    5.4
1       P002  67.0    F    158.0    7.8
2       P003  34.0    F      NaN    5.1
3       P004   NaN    M    145.0    NaN
4       P005  71.0  NaN    162.0    8.2
5       P006  52.0    F      NaN    6.3

In [3]:
# Construire un petit tableau de diagnostic
# .isnull() donne un DataFrame booleen, .sum() somme True/False par colonne
# (True compte comme 1, False comme 0)
manquant = pd.DataFrame({
    "n_manquant":   df.isnull().sum(),
    "pct_manquant": (df.isnull().sum() / len(df) * 100).round(1),
})
manquant

            n_manquant  pct_manquant
patient_id           0           0.0
age                  1          16.7
sexe                 1          16.7
tension              2          33.3
hba1c                1          16.7

## 3. Strategies d'imputation

| Methode             | Quand l'utiliser                                          |
|---------------------|-----------------------------------------------------------|
| **Mediane**         | Variables continues asymétriques (lab, tension, IMC)      |
| **Moyenne**         | Variables continues symétriques (taille adulte)            |
| **Mode**            | Variables catégorielles                                   |
| **Par sous-groupe** | Bonne valeur dependant d'un groupe connu (sexe, age)      |
| **KNN**             | Plusieurs colonnes correlees avec manquements partages    |

Toujours **documenter** la méthode utilisee. Pour les variables critiques, garder un **indicateur de manquement** avant d'imputer.

> **Syntaxe — fillna**
> ```python
> df["col"] = df["col"].fillna(valeur)             # remplace par valeur fixe
> df["col"] = df["col"].fillna(df["col"].median())   # par mediane
> df = df.fillna({"a": 0, "b": "inconnu"})        # plusieurs colonnes
> df = df.copy()                                   # éviter SettingWithCopyWarning
> ```

> **Syntaxe — dropna**
> ```python
> df.dropna()                              # supprime toute ligne avec NaN
> df.dropna(subset=["col1", "col2"])       # seulement si NaN dans ces colonnes
> df.dropna(thresh=3)                      # garde lignes avec >= 3 non-NaN
> ```

In [4]:
df_imp = df.copy()                             # toujours travailler sur une copie

# Mediane pour les valeurs lab (robuste aux extremes)
df_imp["tension"] = df_imp["tension"].fillna(df_imp["tension"].median())
df_imp["hba1c"] = df_imp["hba1c"].fillna(df_imp["hba1c"].median())

# Moyenne pour l'age (a peu près symétrique dans cette cohorte adulte)
df_imp["age"] = df_imp["age"].fillna(df_imp["age"].mean())

# Mode pour la catégorielle
# .mode() peut renvoyer plusieurs valeurs si égalité, on prend la 1ere : [0]
df_imp["sexe"] = df_imp["sexe"].fillna(df_imp["sexe"].mode()[0])
df_imp

  patient_id   age sexe  tension  hba1c
0       P001  45.0    M    128.0    5.4
1       P002  67.0    F    158.0    7.8
2       P003  34.0    F    151.5    5.1
3       P004  53.8    M    145.0    6.3
4       P005  71.0    F    162.0    8.2
5       P006  52.0    F    151.5    6.3

## 4. Validation : plages cliniquement plausibles

On enumere les bornes attendues dans un **dictionnaire** (`col -> (min, max)`) puis on les applique systematiquement.

> **Syntaxe — definition de fonction avec docstring**
> ```python
> def ma_fonction(arg1, arg2):
>     """Une ligne qui resume."""
>     # ... corps ...
>     return résultat
> ```

In [5]:
# Dictionnaire de plages cliniquement acceptables
PLAGES = {
    "age":     (0, 120),         # tuple (min, max)
    "tension": (60, 300),
    "hba1c":   (2.0, 20.0),
}

def valider_plage(df, colonne, lo, hi):
    """Renvoie le sous-DataFrame des lignes hors plage [lo, hi]."""
    # Operateur | == OR booleen vectorise pour pandas
    hors = df[(df[colonne] < lo) | (df[colonne] > hi)]
    if len(hors):
        print(f"  '{colonne}' : {len(hors)} valeur(s) hors [{lo}, {hi}]")
    return hors

# .items() : iterer sur (cle, valeur) d'un dictionnaire
# (lo, hi) : 'unpacking' d'un tuple en 2 variables
for col, (lo, hi) in PLAGES.items():
    if col in df_imp.columns:           # seulement si la colonne existe
        valider_plage(df_imp, col, lo, hi)
print("Validation terminee.")

Validation terminee.

## 5. Pipeline de nettoyage reutilisable

On combine tout dans une seule fonction. Patron : chaque étape prend un DataFrame et en renvoie un. C'est testable, debuggable et explicite sur chaque choix.

> **Syntaxe — argument par défaut**
> ```python
> def f(x, y=10):       # y vaut 10 si non spécifie
>     ...
> f(5)                  # appel avec x=5, y=10
> f(5, y=20)            # appel avec x=5, y=20
> ```

In [6]:
def nettoyer_clinique(df, plages=PLAGES):
    """Pipeline de base : noms, doublons, plages, imputation.

    Parametres
    ----------
    df : pd.DataFrame
        Données brutes.
    plages : dict[str, tuple[float, float]]
        Bornes attendues pour chaque colonne numérique.
    """
    df = df.copy()                       # toujours une copie

    # ---- 1) Noms de colonnes propres ----
    # .str.strip() supprime les espaces aux extremites
    # .str.lower() passe en minuscules
    # .str.replace(" ", "_") remplace espaces par underscores
    df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

    # ---- 2) Supprimer les doublons exacts ----
    avant = len(df)
    df = df.drop_duplicates()
    print(f"  doublons supprimes : {avant - len(df)}")

    # ---- 3) Hors plage -> NaN ----
    for col, (lo, hi) in plages.items():
        if col in df.columns:
            masque = (df[col] < lo) | (df[col] > hi)
            if masque.any():
                print(f"  '{col}' hors plage -> NaN : {int(masque.sum())}")
                # df.loc[ligne, colonne] = valeur
                df.loc[masque, col] = np.nan

    # ---- 4) Imputation mediane sur les colonnes numériques ----
    # .select_dtypes(include="number") garde seulement int/float
    for col in df.select_dtypes(include="number").columns:
        df[col] = df[col].fillna(df[col].median())

    return df


# Demo sur un DataFrame deliberement sale
messy = pd.DataFrame({
    "AGE":     [45, 67, -3, 52, 200, 38],            # -3 et 200 invalides
    "tension": [128, 158, 112, 450, 135, np.nan],   # 450 invalide, 1 NaN
    "hba1c":   [5.4, 7.8, 5.1, 6.3, np.nan, 5.8],
})
nettoyer_clinique(messy)

  doublons supprimes : 0
  'age' hors plage -> NaN : 2
  'tension' hors plage -> NaN : 1

    age  tension  hba1c
0  45.0    128.0    5.4
1  67.0    158.0    7.8
2  48.5    112.0    5.1
3  52.0    131.5    6.3
4  48.5    135.0    5.8
5  38.0    131.5    5.8

## 6. Tendance centrale — moyenne, mediane, mode

| Mesure   | Quand l'utiliser                                |
|----------|-------------------------------------------------|
| Moyenne  | Distribution approximativement symétrique       |
| Mediane  | Distribution asymétrique (lab, duree de sejour) |
| Mode     | Variable catégorielle                           |

**Regle pratique.** Si une valeur extreme deplace la moyenne de plus de quelques pourcents, **rapporter la mediane**.

> **Syntaxe — Series pandas**
> ```python
> s = pd.Series([v1, v2, v3])      # liste -> Series (vecteur 1D)
> s.mean(), s.median(), s.std()    # moyenne, mediane, écart-type
> s.drop(index)                    # supprime un element par index
> ```

In [7]:
# Glycemie a jeun avec une valeur aberrante (saisie erronee : 340)
glycémie = pd.Series([92, 98, 104, 95, 88, 110, 97, 340, 101, 93])

# Comparer moyenne et mediane montre la sensibilité a l'outlier
print(f"Moyenne : {glycémie.mean():.1f}  <- tiree par 340")
print(f"Mediane : {glycémie.median():.1f}  <- robuste")

# .drop(7) supprime l'element a l'index 7 (la valeur 340)
print(f"Sans la valeur aberrante : moyenne = {glycémie.drop(7).mean():.1f}")

Moyenne : 121.8  <- tiree par 340
Mediane : 97.5  <- robuste
Sans la valeur aberrante : moyenne = 97.6

## 7. Dispersion — écart-type, IQR, CV

L'**IQR** (Q3 - Q1) est la dispersion des 50 % du milieu. Robuste aux valeurs extremes, c'est le bon résumé pour les distributions asymétriques (duree de sejour, couts hospitaliers).

Le **coefficient de variation** $CV = \sigma / \mu$ (en %) est sans unite : utile pour comparer la dispersion de variables aux unites différentes.

> **Syntaxe — quantile**
> ```python
> s.quantile(0.5)                  # mediane (50e percentile)
> s.quantile([0.25, 0.75])         # plusieurs en même temps
> q1, q3 = s.quantile([0.25, 0.75])  # unpacking
> ```

In [8]:
# Duree moyenne de sejour (DMS), distribution asymétrique a droite
dms = pd.Series([2, 3, 3, 4, 4, 5, 5, 6, 7, 8, 12, 28, 45])

# Recuperation des quartiles en une ligne (unpacking d'une Series)
q1, q3 = dms.quantile([0.25, 0.75])
print(f"Mediane : {dms.median():.0f} jours")
print(f"IQR     : {q1:.0f}-{q3:.0f} jours")
print(f"Moyenne : {dms.mean():.1f} jours  <- gonflee par 28 et 45")

Mediane : 5 jours
IQR     : 4-8 jours
Moyenne : 10.2 jours  <- gonflee par 28 et 45

## 8. Mesures épidémiologiques

### 8.1 Prevalence

$$P = \frac{\text{cas existants au temps }t}{\text{population au temps }t}$$

Toujours accompagner d'un **intervalle de confiance**. L'approximation normale convient quand $n p (1-p) > 5$.

> **Syntaxe — math.sqrt et puissance**
> ```python
> math.sqrt(x)        # racine carree
> x ** 0.5            # équivalent
> x ** 2              # x au carre
> ```

In [9]:
# Données : 625 diabétiques sur 5,000 enquetes
n_total, n_diabetique = 5_000, 625    # _ comme separateur de milliers

p = n_diabetique / n_total            # proportion brute
se = math.sqrt(p * (1 - p) / n_total) # erreur standard (formule binomiale)

# IC 95% normal : p +/- 1.96 * SE
ci_lo = (p - 1.96 * se) * 100         # en pourcentage
ci_hi = (p + 1.96 * se) * 100

print(f"Prevalence du diabete : {p * 100:.1f}%   IC 95% [{ci_lo:.1f}%, {ci_hi:.1f}%]")

Prevalence du diabete : 12.5%   IC 95% [11.6%, 13.4%]

### 8.2 Taux d'incidence (nouveaux cas par personne-temps)

$$IR = \frac{\text{nouveaux cas pendant la période}}{\text{personnes-années suivies}}$$

Les nouveaux cas suivent une loi de Poisson, d'ou $\text{SE}(IR) = \sqrt{\text{cas}} / \text{PA}$.

In [10]:
# Cohorte TB : 18 nouveaux cas, 850 personnes-années suivies
nouveaux_tb, personne_annees = 18, 850
ir = nouveaux_tb / personne_annees
se = math.sqrt(nouveaux_tb) / personne_annees    # SE Poisson

# On multiplie par 1000 pour une lecture habituelle 'pour 1,000 PA'
ci_lo, ci_hi = (ir - 1.96 * se) * 1000, (ir + 1.96 * se) * 1000
print(f"Incidence TB : {ir * 1000:.1f} pour 1,000 PA")
print(f"IC 95%       : [{ci_lo:.1f}, {ci_hi:.1f}]")

Incidence TB : 21.2 pour 1,000 PA
IC 95%       : [11.4, 31.0]

### 8.3 Ratio de risque (RR) et ratio de cotes (OR)

Tableau 2x2 :

|              | Malade + | Malade - |
|--------------|----------|----------|
| **Expose**   | a        | b        |
| **Non expose** | c      | d        |

$$RR = \frac{a/(a+b)}{c/(c+d)} \qquad OR = \frac{a \cdot d}{b \cdot c}$$

On passe par $\ln$ pour les IC (la distribution de $\ln RR$ et $\ln OR$ est approximativement normale).

> **Syntaxe — fonction qui renvoie un dictionnaire**
> ```python
> def f():
>     return {"résultat": x, "ic": (lo, hi)}    # dict
> r = f()
> r["résultat"], r["ic"]
> ```

In [11]:
def ratio_risque(a, b, c, d, alpha=0.05):
    """Risk ratio avec IC Wald sur l'échelle log."""
    # stats.norm.ppf(p) = quantile p de la loi normale standard
    z = stats.norm.ppf(1 - alpha / 2)         # ~1.96 pour alpha=0.05
    rr = (a / (a + b)) / (c / (c + d))
    se = math.sqrt(1/a - 1/(a+b) + 1/c - 1/(c+d))
    return {
        "RR":    round(rr, 3),
        # math.exp() = e^x, inverse de math.log()
        "IC_lo": round(math.exp(math.log(rr) - z * se), 3),
        "IC_hi": round(math.exp(math.log(rr) + z * se), 3),
    }


def ratio_cotes(a, b, c, d, alpha=0.05):
    """Odds ratio avec IC Wald sur l'échelle log."""
    z = stats.norm.ppf(1 - alpha / 2)
    or_ = (a * d) / (b * c)
    se = math.sqrt(1/a + 1/b + 1/c + 1/d)
    return {
        "OR":    round(or_, 3),
        "IC_lo": round(math.exp(math.log(or_) - z * se), 3),
        "IC_hi": round(math.exp(math.log(or_) + z * se), 3),
    }

# Tabagisme et cancer du poumon (cohorte hypothetique)
# a = fumeurs avec cancer ; b = fumeurs sans cancer
# c = non-fumeurs avec cancer ; d = non-fumeurs sans cancer
print("RR (cohorte)    :", ratio_risque(80, 920, 10, 990))

# Obesite et arthrose du genou (cas-temoin)
print("OR (cas-temoin) :", ratio_cotes(120, 60, 80, 140))

RR (cohorte)    : {'RR': 8.0, 'IC_lo': 4.17, 'IC_hi': 15.348}
OR (cas-temoin) : {'OR': 3.5, 'IC_lo': 2.313, 'IC_hi': 5.296}

## 9. Application — descriptif sur Gapminder

Tableau résumé de l'espérance de vie par continent en 2007.

> **Syntaxe — describe et sélection de colonnes par liste**
> ```python
> df.describe()                          # toutes les colonnes num.
> df.describe(percentiles=[0.25, 0.5, 0.75])  # quartiles
> df_sub = df[["col1", "col2", "col3"]]   # sélection multi-colonnes
> ```

In [12]:
import os
from pathlib import Path
import pandas as pd

# Chemins de cache candidats, dans l'ordre :
#   1. ./data/         (jupyter local, notebook a la racine)
#   2. ../data/        (jupyter local, notebook dans un sous-dossier)
#   3. ./             (au pire on cree un cache dans le cwd)
# En Colab, aucun n'existe : on tombe sur l'URL et on cree ./data/ pour les
# cellules suivantes.
_CANDIDATES = [Path("data"), Path("../data")]
DATA_DIR = next((p for p in _CANDIDATES if p.is_dir()), Path("data"))
DATA_DIR.mkdir(exist_ok=True)


def load_csv(name: str, url: str, **read_csv_kwargs) -> pd.DataFrame:
    """Charge un CSV : cache local d'abord, sinon URL publique.

    Le cache utilise le meme separateur que la lecture (TSV reste TSV).
    """
    for candidate_dir in _CANDIDATES:
        local = candidate_dir / name
        if local.exists():
            return pd.read_csv(local, **read_csv_kwargs)
    df = pd.read_csv(url, **read_csv_kwargs)
    try:
        sep = read_csv_kwargs.get("sep", ",")
        (DATA_DIR / name).parent.mkdir(parents=True, exist_ok=True)
        df.to_csv(DATA_DIR / name, index=False, sep=sep)
    except OSError:
        pass
    return df

GAPMINDER_URL = (
    "https://raw.githubusercontent.com/jennybc/gapminder/"
    "master/inst/extdata/gapminder.tsv"
)
gm = load_csv("gapminder.tsv", GAPMINDER_URL, sep="\t")
recent = gm[gm["year"] == 2007].copy()

# .describe() suit le groupby pour produire un tableau par groupe
resume = (recent.groupby("continent")["lifeExp"]
                .describe(percentiles=[0.25, 0.5, 0.75]).round(1))

# On sélectionné les colonnes utiles
resume[["count", "mean", "std", "min", "25%", "50%", "75%", "max"]]

           count  mean  std   min   25%   50%   75%   max
continent
Africa      52.0  54.8  9.6  39.6  47.8  52.9  59.4  76.4
Americas    25.0  73.6  4.4  60.9  71.8  72.9  76.4  80.7
Asia        33.0  70.7  8.0  43.8  65.5  72.4  75.6  82.6
Europe      30.0  77.6  3.0  71.8  75.0  78.6  79.8  81.8
Oceania      2.0  80.7  0.7  80.2  80.5  80.7  81.0  81.2

## 10. Exercices (avec corriges)

### Exercice 1 — Pipeline sur un jeu artificiel

Appliquez `nettoyer_clinique` sur le DataFrame ci-dessous. Verifiez le rapport et les valeurs imputees.

In [13]:
# Votre essai ici

In [14]:
# Solution
messy = pd.DataFrame({
    "age":     [45, 67, -3, 52, 67, 200, 38, np.nan, 71, 44],
    "tension": [128, 158, 112, 450, 158, 135, 122, np.nan, 162, 118],
    "hba1c":   [5.4, 7.8, 5.1, 6.3, 7.8, np.nan, 5.8, 6.1, 5.2, 5.2],
})
nettoyer_clinique(messy)

  doublons supprimes : 1
  'age' hors plage -> NaN : 2
  'tension' hors plage -> NaN : 1

    age  tension  hba1c
0  45.0    128.0    5.4
1  67.0    158.0    7.8
2  48.5    112.0    5.1
3  52.0    128.0    6.3
5  48.5    135.0    5.6
6  38.0    122.0    5.8
7  48.5    128.0    6.1
8  71.0    162.0    5.2
9  44.0    118.0    5.2

### Exercice 2 — Resume par continent

Pour Gapminder en 2007 : moyenne, mediane et IQR de l'EV par continent.

Indice : on peut passer une **fonction personnalisee** a `.agg()`.

In [15]:
# Votre essai ici

In [16]:
# Solution
# Fonction personnalisee pour l'IQR
def iqr(s):
    return s.quantile(0.75) - s.quantile(0.25)

# .agg accepte une liste qui melange noms de stats et fonctions
(recent.groupby("continent")["lifeExp"]
        .agg(["mean", "median", iqr]).round(2))

            mean  median    iqr
continent
Africa     54.81   52.93  11.61
Americas   73.61   72.90   4.63
Asia       70.73   72.40  10.15
Europe     77.65   78.61   4.78
Oceania    80.72   80.72   0.52

### Exercice 3 — Prevalence avec IC

Une enquete de 2 000 personnes détecté 250 cas. Calculez la prévalence et son IC 95%. Ecrivez une fonction reutilisable.

In [17]:
# Votre essai ici

In [18]:
# Solution
def prevalence_ic(cas, total, confiance=0.95):
    """Prevalence et IC normal a un niveau de confiance donne."""
    p = cas / total
    # stats.norm.ppf : quantile de la loi normale
    z = stats.norm.ppf(0.5 + confiance / 2)
    se = math.sqrt(p * (1 - p) / total)
    return {
        "prévalence": round(p, 4),
        "IC_lo":      round(max(0.0, p - z * se), 4),   # borne >= 0
        "IC_hi":      round(min(1.0, p + z * se), 4),   # borne <= 1
    }

print(prevalence_ic(250, 2000))

{'prévalence': 0.125, 'IC_lo': np.float64(0.1105), 'IC_hi': np.float64(0.1395)}

### Exercice 4 — OR d'une étude cas-temoin

200 cas / 200 temoins ; 140 cas et 80 temoins sont exposes. Calculez l'OR et son IC 95%.

In [19]:
# Votre essai ici

In [20]:
# Solution
# a = cas exposes (140), b = temoins exposes (80),
# c = cas non exposes (200-140=60), d = temoins non exposes (200-80=120)
print(ratio_cotes(140, 80, 60, 120))

{'OR': 3.5, 'IC_lo': 2.313, 'IC_hi': 5.296}

## Resume

Vous savez maintenant :

- diagnostiquer le **mécanisme** des données manquantes ;
- choisir une strategie d'imputation et la documenter ;
- construire un **pipeline de nettoyage** reutilisable ;
- calculer les mesures descriptives et **épidémiologiques** de base (prévalence, incidence, RR/OR) avec leurs IC.

**Suite -> Module 3** : visualisation. Memes données, autre langage.

## Ressources et liens utiles

### Documentation officielle

- **pandas — Working with missing data** — https://pandas.pydata.org/docs/user_guide/missing_data.html
- **pandas — Group by: split-apply-combine** — https://pandas.pydata.org/docs/user_guide/groupby.html
- **scipy.stats** — https://docs.scipy.org/doc/scipy/référence/stats.html

### Methodologie

- **Rubin, D.B. (1976)** *Inference and Missing Data*. Biometrika 63(3): 581-592 — texte fondateur des mécanismes MCAR/MAR/MNAR.
- **Little & Rubin (2019)** *Statistical Analysis with Missing Data*, 3e ed., Wiley — manuel de reference.
- **Weiskopf & Weng (2013)** *Methods and dimensions of electronic health record data quality assessment*, JAMIA 20(1): 144-151 — revue des problèmes de qualité dans les DPI.
- **STROBE Statement** — https://www.strobe-statement.org/ : checklist de rapportage pour études d'observation (cohorte, cas-temoin, transversale).

### Epidemiologie de poche

- **CDC — Principles of Epidemiology in Public Health Practice** (cours en ligne gratuit) — https://www.cdc.gov/csels/dsepd/ss1978/index.html
- **OMS — Indicators of public health** — https://www.who.int/data/gho

### Bibliotheques utilisees

- pandas, numpy, scipy.stats, matplotlib
- Pour des imputations multivariees plus poussees : `sklearn.impute.IterativeImputer` (https://scikit-learn.org/stable/modules/impute.html).

<hr style="margin: 40px 0 16px 0; border: none; border-top: 1px solid #e0e0e0;"><div style="display: flex; justify-content: space-between; align-items: center; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;"><div style="flex: 1; text-align: left;"><a href="module_01_python_pandas.ipynb" style="text-decoration: none; color: #0072B2; font-weight: 500;">&larr; Module 1 : Python et Pandas</a></div><div style="flex: 0; text-align: center; padding: 0 12px;"><a href="index.ipynb" style="text-decoration: none; color: #666666; font-size: 12px;">Sommaire du cours</a></div><div style="flex: 1; text-align: right;"><a href="module_03_visualisation.ipynb" style="text-decoration: none; color: #0072B2; font-weight: 500;">Module 3 : Visualisation &rarr;</a></div></div>